# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.jct-at.com
title: JCT Agricultural Technology 
email: terren.zhou@jct-at.com
author: JCT
description: > # "Write an awesome description for your new site here. 
  JCT is a agricultural technology company providing leading age Aquaponics farming technology.
copyright: 'Copyright &copy; 2018 JCT-AT. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: http://www.facebook.com
  - title: linkedin
    url: http://www.linkedin.com
